sudo: required

services:
  - docker

addons:
  postgresql: "9.6"

python:
  - "3.6"


language: python

script:
  - python3 server/manage.py test

after_success:
  — sh .travis/deploy_dockerhub.sh
  — test “$TRAVIS_BRANCH” = “master” && sh .travis/deploy_heroku.sh