- name: Run task on instance
  hosts: localhost
  tasks:
    - name: get ec2 instance id by its name tag
      ec2_instance:
        aws_access_key: "{{ec2_access_key}}"
        aws_secret_key: "{{ec2_secret_key}}"
        region: us-east-2
        filters:
          tag:Name: "{{ vmID }}"
      register: instances
   
    - name: Run task on remote node
      command: 
        cmd: "python3 ~/task.py {{ expr }} {{ mvars }} {{ expr_pk}} {{server_url}}"
      with_items: "{{instances.instances}}"
