- name: Terminate instances
  hosts: localhost
  tasks:
    - name: get ec2 instance id by its name tag
      ec2_instance:
        aws_access_key: "{{ec2_access_key}}"
        aws_secret_key: "{{ec2_secret_key}}"
        region: us-east-2
        filters:
          tag:Name: "{{ vmID }}"
      register: ec2
    
    - name: Terminate instances 
      ec2:
        aws_access_key: "{{ec2_access_key}}"
        aws_secret_key: "{{ec2_secret_key}}"
        state: 'absent'
        region: us-east-2
        instance_ids: '{{ item.instance_id}}'
      with_items: "{{ec2.instances}}"
